version: '3'

services:

  nifi:
    container_name: nifi
    build:
      context: nifi
    ports:
      - 8080:8080

  nifi-registry:
    container_name: nifi-registry
    build:
      context: nifi-registry
    ports:
      - 18080:18080

  nifi-bootstrap:
    container_name: nifi-bootstrap
    build:
      context: nifi-bootstrap
    command: ["--nifi", "http://nifi:8080", "--registry", "http://nifi-registry:18080"]
